spring.application.name=projeto_integrador

#spring.profiles.active=dev
spring.profiles.active=prod

spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packagesToScan=com.generation.projeto_integrador.controller
springdoc.swagger-ui.use-root-path=true

server.port=${PORT:10000}
